on:
  schedule:
  - cron : '0,30 * * * *'
jobs:
  backup:
    runs-on : ubuntu-latest
    steps:
    - name: Setup Python
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: 
        python-version:  '3.7' 
    - name: install requests
      run: pip install requests
    - name: run backup
      run: python backup.py 
    - name: save file
      run: |
        git config --local user.email 2560814258@qq.com
        git config --local user.name william-song-shy
        git commit -m "backup"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: './backup'
      
      
      
        
    
  
